const userTypes = {
    EMAIL_SIGN_IN_STRAT: 'EMAIL_SIGN_IN_STRAT',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SIGN_IN_SUCCES: 'SIGN_IN_SUCCES',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SING_UP_ERROR: 'SING_UP_ERROR',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
    RESET_AUTH_FORMS: 'RESET_AUTH_FORMS'
};

export default userTypes;