const userTypes = {
    EMAIL_SIGN_IN_STRAT: 'EMAIL_SIGN_IN_STRAT',
    SIGN_IN_SUCCES: 'SIGN_IN_SUCCES',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
    SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SIGN_UP_USER_START: 'SIGN_UP_USER_START',
    USER_ERROR: 'USER_ERROR',

    
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SING_UP_ERROR: 'SING_UP_ERROR',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
    RESET_AUTH_FORMS: 'RESET_AUTH_FORMS'
};

export default userTypes;